name: kurento-media-server
dependencies:
  - name: kms-cmake-utils
    version: ">= 6.7.0"
  - name: kms-core
    version: ">= 6.7.0"
  - name: kms-elements
    version: ">= 6.7.0"
  - name: kms-filters
    version: ">= 6.7.0"
